In [28]:
import json
import pandas as pd

In [7]:
x="""
[{"name": "Alice", "info": {"sex": "F", "age": 38}, "phone": [123, 456]}, 
   {"name": "Ben", "info": {"sex": "M", "age": 45}, "phone": [789]}, 
   {"name": "Cathy", "info": {"sex": "F", "age": 26}, "phone": [987, 234, 135]}]
"""   

In [8]:
x

'\n[{"name": "Alice", "info": {"sex": "F", "age": 38}, "phone": [123, 456]}, \n   {"name": "Ben", "info": {"sex": "M", "age": 45}, "phone": [789]}, \n   {"name": "Cathy", "info": {"sex": "F", "age": 26}, "phone": [987, 234, 135]}]\n'

In [11]:
customers = json.loads(x)
customers

[{'name': 'Alice', 'info': {'sex': 'F', 'age': 38}, 'phone': [123, 456]},
 {'name': 'Ben', 'info': {'sex': 'M', 'age': 45}, 'phone': [789]},
 {'name': 'Cathy', 'info': {'sex': 'F', 'age': 26}, 'phone': [987, 234, 135]}]

In [27]:
for customer in customers:
    print(customer['name'])
    print(customer['info']['age'])
    print(customer['phone'][0])

Alice
38
123
Ben
45
789
Cathy
26
987


In [29]:
pd.read_json(x)

name                     info            phone
0  Alice  {'sex': 'F', 'age': 38}       [123, 456]
1    Ben  {'sex': 'M', 'age': 45}            [789]
2  Cathy  {'sex': 'F', 'age': 26}  [987, 234, 135]

In [35]:
with open('customers.json','w') as f:
    json.dump(customers, f)

In [40]:
with open('customers.json')as json_file:
    data=json.load(json_file)
data

[{'name': 'Alice', 'info': {'sex': 'F', 'age': 38}, 'phone': [123, 456]},
 {'name': 'Ben', 'info': {'sex': 'M', 'age': 45}, 'phone': [789]},
 {'name': 'Cathy', 'info': {'sex': 'F', 'age': 26}, 'phone': [987, 234, 135]}]

In [42]:
import numpy as np

In [43]:
x = np.array([1,2,3])
y = np.array([1,4,9])
z = np.array([[1,2,3],[4,5,6]])
xx = np.array([[1,2,3],[4,5,6],[7,8,8]])

In [9]:
x

array([1, 2, 3])

In [11]:
y


array([1, 4, 9])

In [44]:
z

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
xx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

## len

In [15]:
len(x) #一維是看有幾個元素

3

In [46]:
len(z)#二維是看有幾個row

2

In [47]:
len(xx)

3

## size

In [20]:
x.size #size 是看元素

3

In [22]:
z.size

6

## ndim

In [24]:
z.ndim #ndim 是看維度

2

In [48]:
x.ndim

1

In [49]:
xx.ndim

2

## shape

In [28]:
z.shape #是看幾乘幾的矩陣,row 再column

(2, 3)

In [30]:
x.shape #一維的話就不顯示row，並將column往前放

(3,)

In [50]:
xx.shape

(3, 3)

## data type

In [32]:
x.dtype

dtype('int32')

In [34]:
x.dtype.name

'int32'

In [36]:
np.array([1,2,3], dtype=np.float64)#改成我們要的型態

array([1., 2., 3.])

In [51]:
np.array([1,2,3], dtype=np.int64)

array([1, 2, 3], dtype=int64)

In [52]:
np.array([1,2,3], dtype=np.str)

<ipython-input-52-88e527967d40>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1,2,3], dtype=np.str)


array(['1', '2', '3'], dtype='<U1')

## math

In [41]:
x

array([1, 2, 3])

In [43]:
x+2  #針對整個 array去計算

array([3, 4, 5])

In [45]:
x-2

array([-1,  0,  1])

In [47]:
x*y

array([ 1,  8, 27])

In [49]:
y

array([1, 4, 9])

In [51]:
x+y

array([ 2,  6, 12])

In [53]:
np.add(x,y)

array([ 2,  6, 12])

In [55]:
np.subtract(x,y)#減法

array([ 0, -2, -6])

In [58]:
np.multiply(x,y) #乘法

array([ 1,  8, 27])

In [60]:
np.divide(x,y)#除法

array([1.        , 0.5       , 0.33333333])

In [62]:
np.sqrt(y) #開更號

array([1., 2., 3.])

In [64]:
y **2

array([ 1, 16, 81], dtype=int32)

In [66]:
np.log(x)

array([0.        , 0.69314718, 1.09861229])

In [69]:
np.sum(x)

6

In [71]:
np.cumsum(x)#累加

array([1, 3, 6], dtype=int32)

In [73]:
np.cos(x)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [75]:
np.sin(x)

array([0.84147098, 0.90929743, 0.14112001])

In [77]:
np.tan(x)

array([ 1.55740772, -2.18503986, -0.14254654])

In [81]:
np.mean(x) #平均值

2.0

In [83]:
y

array([1, 4, 9])

In [85]:
np.median(y) #中間數

4.0

In [88]:
np.std(x) #標準差

0.816496580927726

In [90]:
np.var(x)#變異數

0.6666666666666666

In [92]:
np.min(x)#取最小

1

In [94]:
np.min(z)

1

In [97]:
np.min(z,axis=0)# 找column最小

array([1, 2, 3])

In [99]:
np.min(z,axis=1)# 找row最小

array([1, 4])

In [101]:
np.max(z)

6

In [53]:
z

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
zzz=np.array([[3,2,1 ],
       [4, 5, 6]])

In [56]:
np.max(zzz,axis=0)

array([4, 5, 6])

In [103]:
np.max(z,axis=1)

array([3, 6])

In [105]:
np.max(z,axis=0)

array([4, 5, 6])

In [107]:
z

array([[1, 2, 3],
       [4, 5, 6]])

## unique

In [110]:
ran= np.array([1,2,3,4,3,2,1,4,5,2,3,])#去重覆
np.unique(ran)

array([1, 2, 3, 4, 5])

## zeros

In [112]:
np.zeros([2,3])#做數字為0的維度(此例為2*3)

array([[0., 0., 0.],
       [0., 0., 0.]])

## ones

In [114]:
np.ones([4,4])#做4*4數字都為1的維度

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## arange

In [116]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [120]:
np.arange(0,10,3)

array([0, 3, 6, 9])

## random

In [122]:
np.random.random(4)  #從0-1做出幾個數字

array([0.04273758, 0.95572566, 0.51579697, 0.15050176])

In [125]:
np.random.random([2,2]) #做出2*2的隨機矩陣(數字0-1)

array([[0.77626176, 0.28407328],
       [0.13742086, 0.64855805]])

In [128]:
np.random.randint(0,100,10) #0-100間做出幾個數字

array([27,  6, 42, 40, 31, 57, 71, 19, 76, 78])

In [130]:
np.random.randint(0, 100, size=[2,3])#做出2*3的矩陣，數字為0到100

array([[64, 41, 48],
       [34, 89, 69]])

In [134]:
np.random.seed(13)  #固定某種隨機方式，數字出來後怎麼按都一樣
np.random.randint(0, 100, size=[2,3])

array([[82, 48, 74],
       [16, 98, 25]])

In [57]:
np.random.choice(['A','B','C'],size =50)#隨機抽數字嘍

array(['A', 'A', 'A', 'B', 'C', 'A', 'B', 'C', 'C', 'A', 'A', 'C', 'C',
       'C', 'C', 'C', 'B', 'A', 'B', 'B', 'A', 'C', 'A', 'B', 'C', 'C',
       'A', 'A', 'A', 'A', 'B', 'B', 'A', 'A', 'C', 'A', 'B', 'C', 'B',
       'C', 'A', 'A', 'C', 'A', 'C', 'C', 'B', 'B', 'A', 'A'], dtype='<U1')

## sort

In [141]:
a= np.array([3,1,2,4])

In [143]:
a

array([3, 1, 2, 4])

In [145]:
a.sort()  #排序會取代原本的資料

In [146]:
a

array([1, 2, 3, 4])

## reshape

In [148]:
a

array([1, 2, 3, 4])

In [150]:
a.reshape(2,2) #改變排列的呈現方式，但不會更改原資料

array([[1, 2],
       [3, 4]])

## resize

In [151]:
a

array([1, 2, 3, 4])

In [153]:
a.resize(2,2) #resize 會取代原本的資料

In [155]:
a

array([[1, 2],
       [3, 4]])

## append

In [157]:
a= np.array([1,2,3,4,5])#append 只能加在最後面
a

array([1, 2, 3, 4, 5])

In [159]:
np.append(a,6)

array([1, 2, 3, 4, 5, 6])

In [161]:
x

array([1, 2, 3])

In [163]:
np.append(a,x)#增加 但原本資料不會改變

array([1, 2, 3, 4, 5, 1, 2, 3])

In [165]:
a

array([1, 2, 3, 4, 5])

## insert

In [61]:
a=np.array([1, 2, 3, 4, 5, 6])
np.insert(a, 2, 99)#在位置2插入數字99

array([ 1,  2, 99,  3,  4,  5,  6])

In [63]:
a
np.insert(a, 0 ,77)

array([77,  1,  2,  3,  4,  5,  6])

## delete

In [171]:
a

array([1, 2, 3, 4, 5])

In [173]:
np.delete(a,2)刪除位置2的數字

array([1, 2, 4, 5])

In [175]:
a

array([1, 2, 3, 4, 5])

In [177]:
np.delete(a,3)

array([1, 2, 3, 5])

In [180]:
a=np.array([1, 2, 4, 3, 6, 4 ,4 , 4])

In [182]:
np.delete(a,-1)

array([1, 2, 4, 3, 6, 4, 4])

## stack 合併

In [185]:
a= np.array([[1,2],
           [3,4]])
b= np.array([[5,6],
           [7,8]])

In [187]:
## 垂直合併
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [189]:
# 水平合併
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## concatenate合併 同stack

In [191]:
np.concatenate((a,b),axis=0) #垂直

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [193]:
np.concatenate((a,b),axis=1) #水平

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## split 分開

In [65]:
a= np.array([[1,2],
           [3,4]])
a

array([[1, 2],
       [3, 4]])

In [68]:
np.vsplit(a,2)

[array([[1, 2]]), array([[3, 4]])]

In [200]:
a

array([[1, 2],
       [3, 4]])

In [202]:
np.hsplit(a,2)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [204]:
np.split(a,2, axis=0)

[array([[1, 2]]), array([[3, 4]])]

In [205]:
np.split(a,2, axis=1)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

## save & load

In [207]:
z

array([[1, 2, 3],
       [4, 5, 6]])

In [209]:
np.save('datamingL1',z)#存成datamingL1， 存Z的資料

In [212]:
np.load('datamingL1.npy')

array([[1, 2, 3],
       [4, 5, 6]])

## where

In [214]:
np.where(z>3,99,0) #z內的數字大於3的話，就改99 否則就為0

array([[ 0,  0,  0],
       [99, 99, 99]])

In [215]:
np.where(z>3,99,z) #z內的數字大於3的話，就改99 否則就為原z

array([[ 1,  2,  3],
       [99, 99, 99]])

In [ ]:
np.where(z>3,z,z) #z內的數字大於3的話，就為原z 否則就為原z 沒意義~  